---
# Pipeline template
# Includes several jobs
include:
  - project: tooling/ci-templates
    ref: main
    file:
      - detect-secrets.gitlab-ci.yml
      - hadolint.gitlab-ci.yml
      - docker_build.gitlab-ci.yml
      - docker_push.gitlab-ci.yml
      - dive.gitlab-ci.yml
      - dockle.gitlab-ci.yml
      - dependency-check.gitlab-ci.yml

variables:
  DOCKLE_PARMS: "--accept-file settings.py --accept-key ANCHORE_CLI_PASS"
  IMAGE_NAMESPACE: gofwd
  IMAGE_REPOSITORY: ${IMAGE_NAMESPACE}/${CI_PROJECT_NAME}
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  IMAGE_TAR: ${IMAGE_TAG}.tgz

stages:
  # security checks that don't need build
  - sast
  # build the image
  - build
  # security checks after build
  - security_testing
  # test build
  - test
  # push build
  - push

.sast:
  stage: sast

.security_testing:
  stage: security_testing
  needs:
    - build
  variables:
    GIT_STRATEGY: none

test_image:
  stage: test
  needs:
    - build
  script:
    - make test
