---
include:
  - project: tooling/pipeline
    file: docker.yml
    ref: main
  - project: tooling/pipeline
    file: docker_push.yml
    ref: main

variables:
  DOCKLE_PARMS: "--accept-file settings.py"

stages:
  - pre-build lint
  - build
  - post-build lint
  - test
  - push

test:
  stage: test
  dependencies: []
  variables:
    GIT_STRATEGY: none
  image: ${IMAGE_TAG}
  script:
    - anchore-cli --version
    - ansible-lint --version
    - black --version
    - curl --version
    - cyclonedx-py --help
    - detect-secrets --version
    - nikto.pl -Version
    - npm outdated --global
    - pylint --version
    - sonar-scanner --version
    - trufflehog --help
    - yamllint --version
