---
# Job template - to be used in a pipeline by including this file.
#
# Detects whether outdated and insecure libraries are in use by running Dependency-Check.
#
# If the file CONFIGURATION/dependency-check-suppression.xml exists, use it as suppression
#
# Variables:
# CACHE_DIR          General cache directory
# CONFIGURATION      Directory where dependency-check-suppression.xml can be found
# DEPENDENCY_VERSION Specifies which version of owasp/dependency-check is being used

dependency-check:
  # Ensure a "clean" scan environment
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: clone
    DEPENDENCY_SUPPRESSION: "$CONFIGURATION/dependency-check-suppression.xml"
  extends: .security
  image:
    name: owasp/dependency-check:${DEPENDENCY_VERSION}
    entrypoint: [""]
  before_script:
    - mkdir -p reports &>/dev/null || true
    - mkdir -p ${CACHE_DIR}/dependency-check || true
  script:
    - >
      if [[ -f "${DEPENDENCY_SUPPRESSION}" ]]; then
      EXTRA_PARMS="--suppression ${DEPENDENCY_SUPPRESSION}" ;
      else
      EXTRA_PARMS="" ;
      fi ;
      /usr/share/dependency-check/bin/dependency-check.sh
      --data ${CACHE_DIR}/dependency-check
      --enableExperimental
      --exclude "**/*.tgz" --exclude "**/*.zip"
      --failOnCVSS 6
      --format HTML --format JSON
      --out reports
      --project ${CI_PROJECT_NAME}
      --scan . ${EXTRA_PARMS}
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/dependency-check-report.*
  allow_failure: true
