---
# SPDX-License-Identifier: GPL-3.0-or-later
# (c) 2020-2024 Peter Mosmans [Go Forward]
#
# Analyzes a Docker image using Dive.
#
# Variables:
# DIVE_VERSION       Specifies which version of wagoodman/dive is being used
# IMAGE_TAG          Docker image tag

dive:
  extends: .security
  image:
    name: wagoodman/dive:${DIVE_VERSION}
    entrypoint: [""]
  before_script:
    - mkdir -p reports &>/dev/null || true
  script:
    - dive --ci ${IMAGE_TAG} >reports/dive-report.txt
  # Always show report
  after_script:
    - cat reports/dive-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/dive-report.*
  # Only flag the job as failed, not the whole pipeline
  allow_failure: true
