---
# Job template - to be used in a pipeline by including this file.
#
# Builds a Docker image and stores the CycloneDX SBOM file as well as Docker image as tar file
#
# Variables:
# IMAGE_TAG      Docker image tag
# IMAGE_TAR      Name of the Docker image in tar format

build:
  extends: .build
  script:
    - DOCKER_BUILDKIT=1 docker build -t ${IMAGE_TAG} .
    - docker save ${IMAGE_TAG} > ${IMAGE_TAR}
    - temp_container=$(docker create ${IMAGE_TAG})
    - docker cp "$temp_container:/opt/venv/cyclonedx.json" cyclonedx.json
    - docker rm "$temp_container"
  artifacts:
    expire_in: 1 week
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - ${IMAGE_TAR}
      - cyclonedx.json
