---
# SPDX-License-Identifier: GPL-3.0-or-later
# (c) 2020-2024 Peter Mosmans [Go Forward]
#
# Lints a Docker image using Dockle.
# Optional configuration will be read from .dockleignore
#
# Variables:
# DOCKLE_VERSION     Specifies which version of goodwithtech/dockle is being used
# IMAGE_TAR          Name of the Docker image in tar format

dockle:
  variables:
    # We might want to read the .dockleignore file in the root directory
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  extends: .security
  dependencies:
    - build
  image:
    name: goodwithtech/dockle:${DOCKLE_VERSION}
    entrypoint: [""]
  before_script:
    - mkdir -p reports &>/dev/null || true
  script:
    - dockle --input ${IMAGE_TAR} --exit-code 1 > reports/dockle-report.txt
  # Always show report
  after_script:
    - cat reports/dockle-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/dockle-report.*
  # Only flag the job as failed, not the whole pipeline
  allow_failure: true
