---
# Job template - to be used in a pipeline by including this file.
# Make sure to include the .test stage in the pipeline template.
#
# Analyzes a Docker image
#
# include:
#  - .gitlab/docker-analyze.gitlab-ci.yml

analyze_image:
  extends: .security
  dependencies: []
  image:
    name: wagoodman/dive
    entrypoint: [""]
  script:
    - mkdir -p reports || true
    - dive --ci ${IMAGE_TAG} | tee reports/dive-report.txt
  artifacts:
    paths:
      - reports/dive-report.txt
    when: always
