---
# Job template - to be used in a pipeline by including this file.
#
# Lints a Docker image using Dockle.
#
# Variables:
# CONFIGURATION      Directory where .dockleignore can be found
# DOCKLE_VERSION     Specifies which version of goodwithtech/dockle is being used
# IMAGE_TAR          Name of the Docker image in tar format

dockle:
  variables:
    # We might want to read the .dockleignore file in the root directory
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  extends: .security
  dependencies:
    - build
  image:
    name: goodwithtech/dockle:${DOCKLE_VERSION}
    entrypoint: [""]
  script:
    - mkdir -p reports || true
    - >
      if [[ -d "$CONFIGURATION" ]]; then
      cd "${CONFIGURATION}" ;
      dockle --input ../${IMAGE_TAR} --exit-code 1 |
      tee ../reports/dockle-report.txt ;
      else
      dockle --input ${IMAGE_TAR} --exit-code 1 |
      tee reports/dockle-report.txt ;
      fi
  artifacts:
    when: always
    paths:
      - reports/dockle-report.txt

