---
# Job template - to be used in a pipeline by including this file.
# Make sure to include the build stage in the pipeline template.
#
# Builds a Docker image and stores the package-lock.json file
#
# include:
#  - .gitlab/docker-build.gitlab-ci.yml

build:
  stage: build
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  script:
    - docker build -t ${IMAGE_TAG} .
    - docker save ${IMAGE_TAG} | gzip > ${IMAGE_TAR}
    # - temp_container=$(docker create ${IMAGE_TAG})
    # - docker cp "$temp_container:/usr/local/lib/node_nomdules/npm/node_modules/juice-shop/package-lock.json" package-lock.json
    # - docker rm "$temp_container"
  artifacts:
    expire_in: 1 week
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      # - package-lock.json
      - ${IMAGE_TAR}
