---
# SPDX-License-Identifier: GPL-3.0-or-later
# (c) 2020-2024 Peter Mosmans [Go Forward]
#
# Analyzes a Docker image using Grype.
# Optional configuration will be read from .grype.yaml
#
# Variables:
# CACHE_DIR          General cache directory
# IMAGE_TAR          Name of the Docker image (in tar format)
# TOOLS_VERSION      Specifies which version of gofwd/tools-image is being used

grype:
  variables:
    # We might want to read the .grype.yaml file in the root directory
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  extends: .security
  image: gofwd/tools-image:${TOOLS_VERSION}
  before_script:
    - mkdir -p reports &>/dev/null || true
  script:
    - >
      GRYPE_DB_CACHE_DIR=${CACHE_DIR}/grype
      grype docker-archive:${IMAGE_TAR}
      --output json=reports/grype-report.json
      --output table=reports/grype-report.txt
      --output template=reports/grype-report.html
      -t /usr/local/lib/html-table.tmpl
      --fail-on medium
  # Always show report
  after_script:
    - cat reports/grype-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/grype-report.*
  # Continue other tests, even if this one fails
  allow_failure: true
