---
# Job template - to be used in a pipeline by including this file.
#
# Analyzes a Docker image using Grype.
#
# Variables:
# CACHE_DIR          General cache directory
# IMAGE_TAR     Name of the Docker image (in tar format)
# TOOLS_VERSION Specifies which version of gofwd/tools-image is being used

grype:
  extends: .security
  image: gofwd/tools-image:$TOOLS_VERSION
  before_script:
    - mkdir -p reports 1>/dev/null || true
  script:
    - >
      GRYPE_DB_CACHE_DIR=${CACHE_DIR}/grype
      grype docker-archive:${IMAGE_TAR}
      --output json=reports/grype-report.json
      --output table=reports/grype-report.txt
      --output template=reports/grype-report.html
      -t /usr/local/lib/html-table.tmpl
      --fail-on medium
  # Always show report
  after_script:
    - cat reports/grype-report.txt
  # Continue other tests, even if this one fails
  allow_failure: true
  artifacts:
    paths:
      - reports/grype-report.*
    when: always
