---
# Job template - to be used in a pipeline by including this file.
#
# Lints a Dockerfile using hadolint.
#
# Variables:
# CONFIGURATION      Directory where .hadolint.yaml can be found
# HADOLINT_VERSION   Specifies which version of hadolint/hadolint is being used

hadolint:
  extends: .sast
  dependencies: []
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  image:
    name: hadolint/hadolint:${HADOLINT_VERSION}
  script:
    - mkdir -p reports || true
    # Check if the configuration directory exists and if so, execute from there
    # This allows the configuration file .hadolint.yaml to be read
    - >
      if [[ -d "$CONFIGURATION" ]]; then
      cd "${CONFIGURATION}" ;
      hadolint ../Dockerfile -f sonarqube |
      tee ../reports/hadolint-report.json ;
      else
      hadolint Dockerfile -f sonarqube |
      tee reports/hadolint-report.json ;
      fi
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/hadolint-report.json
