---
# Job template - to be used in a pipeline by including this file.
#
# Lints a Dockerfile using hadolint.
#
# Variables:
# HADOLINT_VERSION Specifies which version of hadolint/hadolint is being used

hadolint:
  extends: .sast
  dependencies: []
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  image:
    name: hadolint/hadolint:${HADOLINT_VERSION}
  script:
    - mkdir -p reports || true
    - hadolint Dockerfile | tee reports/hadolint-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/hadolint-report.txt
