---
# Job template - to be used in a pipeline by including this file.
#
# Tests a Docker image using "make test".
#
# Variables:
# IMAGE_TAG      Docker image tag

test:
  extends: .test
  image:
    name: ${IMAGE_TAG}
    entrypoint: [""]
  script:
    - make test
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
